Create swerve subsystem
frc2357/FRC-2023-Cowtown-Robot pull request #5
Opened 2023-09-10 04:35 UTC by Tyson453

2023-10-19 18:29 UTC, coderkevin requested changes
Can you remove the non-swerve code from this PR please? I'm seeing a lot of limelight code, some shooter stuff, and intake stuff. Let's keep each PR to a given task, please.

2023-10-21 03:06 UTC, Tyson453 commented
This branch needs be tested one more time then can be merged to main.

2023-10-21 15:11 UTC, coderkevin requested changes
Still have code in here that doesn't belong.

Also, this PR is now removing intake/shooter code when it should probably just leave it alone.

2023-10-21 15:11 UTC, coderkevin commented on cowtown2023/src/main/java/com/team2357/frc2023/Robot.java
> +    while (System.currentTimeMillis() - disabledStart != Constants.SWERVE.DISABLED_WAIT_TO_BREAK_MILLIS);
Long-term, we'll want to use a TimerTask for this instead of blocking the main thread.

2023-10-21 15:11 UTC, coderkevin commented on cowtown2023/src/main/java/com/team2357/lib/subsystems/DualLimelightManagerSubsystem.java
> +package com.team2357.lib.subsystems;
This shouldn't be part of this PR

2023-10-21 15:11 UTC, coderkevin commented on cowtown2023/src/main/java/com/team2357/lib/subsystems/LimelightSubsystem.java
This shouldn't be part of this PR

2023-10-21 15:11 UTC, coderkevin commented on cowtown2023/src/main/java/com/team2357/lib/subsystems/TogglableLimelightSubsystem.java
>  package com.team2357.lib.subsystems;
This shouldn't be part of this PR.

2023-10-21 15:11 UTC, coderkevin commented on cowtown2023/vendordeps/NavX.json
> +{
Why is navx here? We don't use this.

2023-10-21 17:37 UTC, coderkevin approved these changes
Looks good!

2023-10-21 17:38 UTC, merged